imports:
    - { resource: parameters.yaml }
    - { resource: security.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    default_locale: en
    locales: [de, en]

framework:
    secret: '%kernel.secret%'
    session: ~
    # JMS\TranslationBundle\JMSTranslationBundle needs validation
    validation: ~
    # knp_paginator needs translate bundle
    translator: { fallbacks: ['%default_locale%'], logging: false }
    profiler: { only_exceptions: false }
    http_client:
        scoped_clients:
            # see: https://symfony.com/doc/current/reference/configuration/framework.html#reference-http-client-scoped-clients
            admin.client:
                base_uri: '%app.site.base_uri%'
                auth_basic: '%app.site.auth_basic%'

twig:
    globals:
        siteName: '%app.site.name%'
        siteHeader: '%app.site.name% - Administration'
        locales: "%locales%"
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']

scssphp:
    assets:
        "css/base.css":
            src: "public/assets/scss/base.scss"
            sourceMap: true
#            importPaths:
#                - "vendor/twbs/bootstrap/scss"
#            variables:
#                primary: '#ff0066'

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

