imports:
    - { resource: parameters.yaml }
    - { resource: security.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    default_locale: en
    locales: [de, en]

framework:
    secret: '%kernel.secret%'
    session:
        storage_factory_id: session.storage.factory.native
        # Not setting either "framework.session.handler_id" or "save_path" config options is deprecated; "handler_id" will default to null in 7.0 if "save_path" is not set and to "session.handler.native_file" otherwise.
        handler_id: null
        # Not setting the "framework.session.cookie_secure" config option is deprecated. It will default to "auto" in 7.0.
        cookie_secure: auto
        # Not setting the "framework.session.cookie_samesite" config option is deprecated. It will default to "lax" in 7.0.
        cookie_samesite: lax
    php_errors:
        # Not setting the "framework.php_errors.log" config option is deprecated. It will default to "true" in 7.0.
        log: true
    # LoginFormAuthenticator checks for csrf_protection
    csrf_protection: ~
    # Not setting the "framework.http_method_override" config option is deprecated. It will default to "false" in 7.0.
    http_method_override: false
    # Not setting the "framework.handle_all_throwables" config option is deprecated. It will default to "true" in 7.0.
    handle_all_throwables: true
    annotations: false
    # JMS\TranslationBundle\JMSTranslationBundle needs validation
    validation:
        # Not setting the "framework.validation.email_validation_mode" config option is deprecated. It will default to "html5" in 7.0.
        email_validation_mode: html5
    # knp_paginator needs translate bundle
    translator: { fallbacks: ['%default_locale%'], logging: false }
    profiler: { only_exceptions: false }
    router:
        utf8: true
    http_client:
        scoped_clients:
            # see: https://symfony.com/doc/current/reference/configuration/framework.html#reference-http-client-scoped-clients
            admin.client:
                base_uri: '%app.site.base_uri%'
                auth_basic: '%app.site.auth_basic%'

twig:
    globals:
        siteName: '%app.site.name%'
        siteHeader: '%app.site.name% - Administration'
        locales: "%locales%"
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    strict_variables: '%kernel.debug%'
    exception_controller: null  # as per https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md#twigbundle

scssphp:
    assets:
        "css/base.css":
            src: "public/assets/scss/base.scss"
            sourceMap: true

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

fs_solr:
    endpoints:
        core_de:
            host: localhost
            port: 8983
            path: /
            core: "%app.site.key%_de"
            timeout: 600
        core_en:
            host: localhost
            port: 8983
            path: /
            core: "%app.site.key%_en"
            timeout: 600
