# config/security.yaml

# see https://symfony.com/doc/5.2/security/experimental_authenticators.html
security:
    enable_authenticator_manager: true

    providers:
        # see https://symfony.com/doc/5.4/security/custom_provider.html
        existdb_provider:
            id: App\Security\User\ExistDbUserProvider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: /api/dts
            guard:
                authenticators:
                    - App\Security\BasicAuthAuthenticator

        main:
            pattern: ^/
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path:   logout
                target: /
        
    access_control:
        - { path: ^/(login|logout)$, role: PUBLIC_ACCESS }
        - { path: ^/(de)/(login|logout)$, role: PUBLIC_ACCESS }
        - { path: ^/(convert)$, role: PUBLIC_ACCESS }
        - { path: ^/(de)/(convert)$, role: PUBLIC_ACCESS }
        - { path: ^/, role: ROLE_USER }