# config/security.yaml

# see https://symfony.com/doc/4.4/security.html
security:
    providers:
        # see https://symfony.com/doc/current/security/custom_provider.html
        existdb_provider:
            id: App\Security\User\ExistDbUserProvider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
                        
        main:
            anonymous: ~
            pattern: ^/
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path:   logout
                target: /
        
    access_control:
        - { path: ^/(login|logout)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(de)/(login|logout)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(word2tei)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }