# config/services.yaml
services:
    # the following two configurations are needed for command-classes to be automatically
    # registered as services, see
    #   https://symfony.com/doc/3.4/console/commands_as_services.html
    # default configuration for services in *this* file
    
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $siteKey: '%app.site.key%' # so we can inject this one, https://symfony.com/blog/new-in-symfony-3-4-local-service-binding
            
    Jasny\Twig\PcreExtension:
        tags:
          - { name: twig.extension }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # additional services
    App\Menu\Builder:
        arguments: [ "@knp_menu.factory", "@security.authorization_checker", "@translator", "@request_stack", "%app.zotero.options%" ]
        tags:
            # The alias is what is used to retrieve the menu in twig
            - { name: knp_menu.menu_builder, method: createTopMenu, alias: top }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createBreadcrumbMenu, alias: breadcrumb }
            - { name: knp_menu.menu_builder, method: createFooterMainMenu, alias: footer-main }

    App\Service\ExistDbClientService:
        arguments:
            $options: "%app.existdb.options%"

    App\Service\ZoteroApiService:
        arguments:
            $options: "%app.zotero.options%"
            
    App\Service\CollectiveAccessService:
        arguments:
            $options: "%app.collective-access.options%"
            
    App\Utils\PandocProcessor:
        arguments:  [ "%app.pandoc.processor.arguments%" ]

    App\Utils\PandocConverter:
        arguments:  [ "%app.pandoc.processor.arguments%" ]

    app.image-conversion-provider:
        class: "%app.image-conversion-provider.class%"
        arguments:  [ "%app.image-conversion-provider.arguments%" ]

    App\Service\ImageConversion\ConversionService:
        calls:
            - [ addProvider, [ '@app.image-conversion-provider' ]]

    App\Utils\AnvcScalarClient:
        arguments: [ "%app.scalar_client.options%" ]

    App\Utils\MpdfConverter:
        arguments: [ "%app.mpdf-converter.arguments%" ]

    app.xsl-converter-adapter:
        class: "%app.xsl-converter-adapter.class%"
        arguments:  [ "%app.xsl-converter-adapter.arguments%" ]

    App\Utils\XslConverter:
        calls:
            - [ setOption, [ 'adapter', '@app.xsl-converter-adapter' ]]

    app.tei-prettyprinter-adapter:
        class: "%app.tei-prettyprinter-adapter.class%"
        arguments:  [ "%app.tei-prettyprinter-adapter.arguments%" ]

    App\Utils\XmlPrettyPrinter\XmlPrettyPrinter:
        calls:
            - [ setAdapter, [ '@app.tei-prettyprinter-adapter' ]]
    
    # So we can inject @solr.client, see https://github.com/floriansemm/SolrBundle/issues/191#issuecomment-466101623
    FS\SolrBundle\SolrInterface: '@solr.client'
    
    # Override hydrator, see https://symfony.com/doc/4.4/service_container/service_decoration.html
    solr.doctrine.hydration.no_database_value_hydrator:
        class: App\Search\NoDatabaseValueHydratorWithChildren
        arguments: [ '@solr.meta.information.factory' ]
